### ISSUE TITLE
Use heigher value for PASSPHRASE_ENCRYPTION_ITERATIONS_DEFAULT

### ISSUE THREAD

**Issue by webmaster128** [karek314/lisk-php#4]
PASSPHRASE_ENCRYPTION_ITERATIONS_DEFAULT is set to 1 at the moment, which basically means no computation time for the password -> AES key operation. In order to get proper security, a user must choose a 128 bit entropy password or stronger. I don't think that's a good assumption.

PASSPHRASE_ENCRYPTION_ITERATIONS_DEFAULT should be as high as possible while making without annoying the user too much. In the Lisk core issue related to key derivation, we were talking about 1,000,000 iterations, which takes about 800 ms to perform. I think this is a good default because 800ms is fast enough when enabling forging and it makes brute force attacks roughly 1,000,000x times harder.

The reason iterations is set to 1 in the Lisk core test data is that they do not want to wait 101*800ms when running tests.

**Comment by karek314** [comment]
I agree, this shouldn't be constant, i will soon address it, but i think it's unnecessary high by default in lisk-js, It does take too long to compute, it's too big cost when it comes to forging failover scripts and it's efficiency and essentially, brute-forcing forging position has no real economic incentive in my opinion, rendering those encryption efforts purely wasted. In 0.9.X there is plain passphrase in config.json or sent via SSL to toggle forging and yet, it was never hacked. Attacking forging position to gain access to account forging feature is useless because:

- Most accounts are protected by second passphrase before accessing funds

- Hacked account can be easily down voted by community (no long term hack benefit)

- Forging delegate accounts usually are not cold wallets

There is many easier and cheaper attacks to perform on Lisk like, unclaimed accounts, 2^64 effort and there is one 1.6m LSK wallet unclaimed ;)

**Comment by webmaster128** [comment]
I agree that the whole encryption is questionable at this point. HQ devs said this protects you from someone who gains read access to the node's filesystem (backups, cloud providers, ...).

However, I think when something is encrypted, the user can expect that it is safe to publish. And thus check in the encrypted password in config repositories or similar. Thus, a default value should give the user a very good security while reducing the parameter can be done when very high entropy passwords are used. For this reason I suggest setting the default parameter to 1,000,000 or at least 100,000.

**Comment by bigvito19** [comment]
Does using the vanity can perform the 2^64 attack?

**Comment by karek314** [comment]
@webmaster128 Fair point, 1,000,000 set, can be easily reduced if needed.
https://github.com/karek314/lisk-php/commit/2fe32e87cbc296e35b742dbb85338f97e76d383a

@bigvito19 With lisk-php vanity, highly unlikely - it's side feature in lisk-php, its slow, you should looking for very good implementation in opencl.
